# Generated by Django 6.0.6 on 2026-09-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_department_person_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee', models.ManyToManyField(related_name='skills', to='home.employee')),
            ],
        ),
    ]
