# Generated by Django 6.0.6 on 2026-09-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
