# Generated by Django 6.0.6 on 2026-09-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='employees', to='home.skills'),
        ),
    ]
